//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_TicaretDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRE
    {
        public int ID { get; set; }
        public int USERID { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public Nullable<int> CITYID { get; set; }
        public Nullable<int> TOWNID { get; set; }
        public Nullable<short> NO { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual TOWN TOWN { get; set; }
        public virtual USER_ USER_ { get; set; }
    }
}
