//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_TicaretDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAIL
    {
        public int ID { get; set; }
        public int ORDERId { get; set; }
        public int PRODUCTId { get; set; }
        public short AMOUNT { get; set; }
        public double PRICE { get; set; }
        public double TOTAL { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
