//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_TicaretDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ORDERDETAILS = new HashSet<ORDERDETAIL>();
        }
    
        public int ID { get; set; }
        public string PRODUCTCODE { get; set; }
        public string PRODUCTNAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<int> CATEGORYId { get; set; }
        public Nullable<int> SUBCATEGORYId { get; set; }
        public Nullable<int> STOCK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILS { get; set; }
        public virtual PRODUCTCATEGORY PRODUCTCATEGORY { get; set; }
        public virtual PRODUCTSUBCATEGORY PRODUCTSUBCATEGORY { get; set; }
    }
}
