//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_TicaretDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOWN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOWN()
        {
            this.ADDRES = new HashSet<ADDRE>();
        }
    
        public int ID { get; set; }
        public string TOWN1 { get; set; }
        public int CITYId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADDRE> ADDRES { get; set; }
        public virtual CITY CITY { get; set; }
    }
}
